version: '3'

services:
    mssql:
        image: microsoft/mssql-server-linux:latest
        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=YourStrong!Passw0rd
        ports:
            - 1433:1433
        volumes:
            - /var/opt/mssql

    webserver:
        image: docker-airflow:latest
        restart: always
        depends_on:
            - mssql
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=${SQL_ALCHEMY_CONN}
            - AIRFLOW__CELERY__RESULT_BACKEND=${CELERY_RESULTS_BACKEND}
        volumes:
            - ./dags:/usr/local/airflow/dags
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
